name: packagemanager
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  expandable:
  get: ^4.6.5
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  eva_icons_flutter: ^3.1.0
  line_icons: ^2.0.1
  http: ^0.13.5
  hive: ^2.2.3
  shimmer: ^2.0.0
  intl:
  dio: ^4.0.6
  sqflite: ^2.0.3+1
  flutter_native_splash: ^2.2.7
  font_awesome_flutter:
  validators: ^3.0.0
  path_provider:
  path:
  url_launcher:
  extended_masked_text: ^2.3.1
  get_it: ^7.2.0
  carousel_slider: ^4.1.1
  sliding_up_panel: ^2.0.0+1
  objectbox:
  objectbox_flutter_libs:
  connectivity_plus:
  loading_animation_widget:
  connectivity_wrapper:
  flutter_barcode_scanner:
  flutter_expandable_fab:
  uuid:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdf: ^20.2.43
  pdf: ^3.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  objectbox_generator:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
